// mkerrors.sh
// Code generated by the command above; see README.md. DO NOT EDIT.

//go:build amd64 && haiku
// +build amd64,haiku

// Created by cgo -godefs - DO NOT EDIT
// cgo -godefs -- _const.go

package unix

import "syscall"

const (
	AF_APPLETALK              = 0x2
	AF_BLUETOOTH              = 0xa
	AF_DLI                    = 0x6
	AF_INET                   = 0x1
	AF_INET6                  = 0x5
	AF_IPX                    = 0x7
	AF_LINK                   = 0x4
	AF_LOCAL                  = 0x9
	AF_MAX                    = 0xb
	AF_NOTIFY                 = 0x8
	AF_ROUTE                  = 0x3
	AF_UNIX                   = 0x9
	AF_UNSPEC                 = 0x0
	B0                        = 0x0
	B110                      = 0x3
	B115200                   = 0x11
	B1200                     = 0x9
	B134                      = 0x4
	B150                      = 0x5
	B1800                     = 0xa
	B19200                    = 0xe
	B200                      = 0x6
	B230400                   = 0x12
	B2400                     = 0xb
	B300                      = 0x7
	B31250                    = 0x13
	B38400                    = 0xf
	B4800                     = 0xc
	B50                       = 0x1
	B57600                    = 0x10
	B600                      = 0x8
	B75                       = 0x2
	B9600                     = 0xd
	BRKINT                    = 0x2
	BS0                       = 0x0
	BS1                       = 0x2000
	BSDLY                     = 0x2000
	CBAUD                     = 0x1f
	CLOCAL                    = 0x800
	CLOCK_MONOTONIC           = 0x0
	CLOCK_PROCESS_CPUTIME_ID  = -0x2
	CLOCK_REALTIME            = -0x1
	CLOCK_THREAD_CPUTIME_ID   = -0x3
	CR0                       = 0x0
	CR1                       = 0x200
	CR2                       = 0x400
	CR3                       = 0x600
	CRDLY                     = 0x600
	CREAD                     = 0x80
	CRTSCTS                   = 0x6000
	CS5                       = 0x0
	CS6                       = 0x0
	CS7                       = 0x0
	CS8                       = 0x20
	CSIZE                     = 0x20
	CSTOPB                    = 0x40
	ECHO                      = 0x8
	ECHOCTL                   = 0x400
	ECHOE                     = 0x10
	ECHOK                     = 0x20
	ECHOKE                    = 0x1000
	ECHONL                    = 0x40
	ECHOPRT                   = 0x800
	EV_BREAK                  = 0x2
	EV_CARRIER                = 0x4
	EV_CARRIERLOST            = 0x8
	EV_RING                   = 0x1
	FD_CLOEXEC                = 0x1
	FD_SETSIZE                = 0x400
	FF0                       = 0x0
	FF1                       = 0x8000
	FFDLY                     = 0x8000
	FLUSHO                    = 0x2000
	F_DUPFD                   = 0x1
	F_DUPFD_CLOEXEC           = 0x200
	F_GETFD                   = 0x2
	F_GETFL                   = 0x8
	F_GETLK                   = 0x20
	F_LOCK                    = 0x1
	F_OK                      = 0x0
	F_RDLCK                   = 0x40
	F_SETFD                   = 0x4
	F_SETFL                   = 0x10
	F_SETLK                   = 0x80
	F_SETLKW                  = 0x100
	F_TEST                    = 0x3
	F_TLOCK                   = 0x2
	F_ULOCK                   = 0x0
	F_UNLCK                   = 0x200
	F_WRLCK                   = 0x400
	HUPCL                     = 0x400
	ICANON                    = 0x2
	ICRNL                     = 0x100
	IEXTEN                    = 0x200
	IFF_ALLMULTI              = 0x200
	IFF_AUTOUP                = 0x80
	IFF_AUTO_CONFIGURED       = 0x2000
	IFF_BROADCAST             = 0x2
	IFF_CONFIGURING           = 0x4000
	IFF_LINK                  = 0x1000
	IFF_LOOPBACK              = 0x8
	IFF_MULTICAST             = 0x8000
	IFF_NOARP                 = 0x40
	IFF_POINTOPOINT           = 0x10
	IFF_PROMISC               = 0x100
	IFF_SIMPLEX               = 0x800
	IFF_UP                    = 0x1
	IFNAMSIZ                  = 0x20
	IGNBRK                    = 0x1
	IGNCR                     = 0x80
	IGNPAR                    = 0x4
	INLCR                     = 0x40
	INPCK                     = 0x10
	IN_CLASSA_HOST            = 0xffffff
	IN_CLASSA_MAX             = 0x80
	IN_CLASSA_NET             = 0xff000000
	IN_CLASSA_NSHIFT          = 0x18
	IN_CLASSB_HOST            = 0xffff
	IN_CLASSB_MAX             = 0x10000
	IN_CLASSB_NET             = 0xffff0000
	IN_CLASSB_NSHIFT          = 0x10
	IN_CLASSC_HOST            = 0xff
	IN_CLASSC_NET             = 0xffffff00
	IN_CLASSC_NSHIFT          = 0x8
	IN_CLASSD_HOST            = 0xfffffff
	IN_CLASSD_NET             = 0xf0000000
	IN_CLASSD_NSHIFT          = 0x1c
	IN_LOOPBACKNET            = 0x7f
	IPPROTO_AH                = 0x33
	IPPROTO_DSTOPTS           = 0x3c
	IPPROTO_ESP               = 0x32
	IPPROTO_ETHERIP           = 0x61
	IPPROTO_FRAGMENT          = 0x2c
	IPPROTO_HOPOPTS           = 0x0
	IPPROTO_ICMP              = 0x1
	IPPROTO_ICMPV6            = 0x3a
	IPPROTO_IGMP              = 0x2
	IPPROTO_IP                = 0x0
	IPPROTO_IPV6              = 0x29
	IPPROTO_MAX               = 0x100
	IPPROTO_NONE              = 0x3b
	IPPROTO_RAW               = 0xff
	IPPROTO_ROUTING           = 0x2b
	IPPROTO_TCP               = 0x6
	IPPROTO_UDP               = 0x11
	IPV6_DEFHLIM              = 0x40
	IPV6_DSTOPTS              = 0x24
	IPV6_FLOWINFO_MASK        = 0xffffff0f
	IPV6_FLOWLABEL_MASK       = 0xffff0f00
	IPV6_FRAGTTL              = 0x78
	IPV6_HLIMDEC              = 0x1
	IPV6_HOPLIMIT             = 0x21
	IPV6_HOPOPTS              = 0x23
	IPV6_JOIN_GROUP           = 0x1c
	IPV6_LEAVE_GROUP          = 0x1d
	IPV6_MAXHLIM              = 0xff
	IPV6_MAXOPTHDR            = 0x800
	IPV6_MAXPACKET            = 0xffff
	IPV6_MMTU                 = 0x500
	IPV6_MULTICAST_HOPS       = 0x19
	IPV6_MULTICAST_IF         = 0x18
	IPV6_MULTICAST_LOOP       = 0x1a
	IPV6_PKTINFO              = 0x1f
	IPV6_RECVHOPLIMIT         = 0x22
	IPV6_RECVPKTINFO          = 0x20
	IPV6_RTHDR                = 0x25
	IPV6_UNICAST_HOPS         = 0x1b
	IPV6_V6ONLY               = 0x1e
	IPV6_VERSION              = 0x60
	IPV6_VERSION_MASK         = 0xf0
	IP_ADD_MEMBERSHIP         = 0xc
	IP_ADD_SOURCE_MEMBERSHIP  = 0x10
	IP_BLOCK_SOURCE           = 0xe
	IP_DF                     = 0x4000
	IP_DROP_MEMBERSHIP        = 0xd
	IP_DROP_SOURCE_MEMBERSHIP = 0x11
	IP_HDRINCL                = 0x2
	IP_MAXPACKET              = 0xffff
	IP_MAX_MEMBERSHIPS        = 0x14
	IP_MF                     = 0x2000
	IP_MSS                    = 0x240
	IP_MULTICAST_IF           = 0x9
	IP_MULTICAST_LOOP         = 0xb
	IP_MULTICAST_TTL          = 0xa
	IP_OFFMASK                = 0x1fff
	IP_OPTIONS                = 0x1
	IP_RECVDSTADDR            = 0x7
	IP_RECVOPTS               = 0x5
	IP_RECVRETOPTS            = 0x6
	IP_RETOPTS                = 0x8
	IP_TOS                    = 0x3
	IP_TTL                    = 0x4
	IP_UNBLOCK_SOURCE         = 0xf
	ISIG                      = 0x1
	ISTRIP                    = 0x20
	ITIMER_PROF               = 0x3
	ITIMER_REAL               = 0x1
	ITIMER_VIRTUAL            = 0x2
	IUCLC                     = 0x200
	IXANY                     = 0x800
	IXOFF                     = 0x1000
	IXON                      = 0x400
	LOCK_EX                   = 0x2
	LOCK_NB                   = 0x4
	LOCK_SH                   = 0x1
	LOCK_UN                   = 0x8
	MADV_DONTNEED             = 0x5
	MADV_FREE                 = 0x6
	MADV_NORMAL               = 0x1
	MADV_RANDOM               = 0x3
	MADV_SEQUENTIAL           = 0x2
	MADV_WILLNEED             = 0x4
	MAP_ANON                  = 0x8
	MAP_ANONYMOUS             = 0x8
	MAP_FIXED                 = 0x4
	MAP_NORESERVE             = 0x10
	MAP_PRIVATE               = 0x2
	MAP_SHARED                = 0x1
	MCAST_BLOCK_SOURCE        = 0x13
	MCAST_JOIN_GROUP          = 0x12
	MCAST_JOIN_SOURCE_GROUP   = 0x16
	MCAST_LEAVE_GROUP         = 0x15
	MCAST_LEAVE_SOURCE_GROUP  = 0x17
	MCAST_UNBLOCK_SOURCE      = 0x14
	MSG_BCAST                 = 0x100
	MSG_CTRUNC                = 0x20
	MSG_DONTROUTE             = 0x4
	MSG_DONTWAIT              = 0x80
	MSG_EOF                   = 0x400
	MSG_EOR                   = 0x8
	MSG_MCAST                 = 0x200
	MSG_NOSIGNAL              = 0x800
	MSG_OOB                   = 0x1
	MSG_PEEK                  = 0x2
	MSG_TRUNC                 = 0x10
	MSG_WAITALL               = 0x40
	MS_ASYNC                  = 0x1
	MS_INVALIDATE             = 0x4
	MS_SYNC                   = 0x2
	NAME_MAX                  = 0x100
	NFDBITS                   = 0x20
	NL0                       = 0x0
	NL1                       = 0x100
	NLDLY                     = 0x100
	NOFLSH                    = 0x80
	OCRNL                     = 0x8
	OFDEL                     = 0x80
	OFILL                     = 0x40
	OLCUC                     = 0x2
	ONLCR                     = 0x4
	ONLRET                    = 0x20
	ONOCR                     = 0x10
	OPOST                     = 0x1
	O_ACCMODE                 = 0x3
	O_APPEND                  = 0x800
	O_CLOEXEC                 = 0x40
	O_CREAT                   = 0x200
	O_DIRECT                  = 0x100000
	O_DIRECTORY               = 0x200000
	O_DSYNC                   = 0x40000
	O_EXCL                    = 0x100
	O_NDELAY                  = 0x80
	O_NOCACHE                 = 0x100000
	O_NOCTTY                  = 0x1000
	O_NOFOLLOW                = 0x80000
	O_NONBLOCK                = 0x80
	O_NOTRAVERSE              = 0x2000
	O_RDONLY                  = 0x0
	O_RDWR                    = 0x2
	O_RSYNC                   = 0x20000
	O_RWMASK                  = 0x3
	O_SYNC                    = 0x10000
	O_TRUNC                   = 0x400
	O_WRONLY                  = 0x1
	PARENB                    = 0x100
	PARMRK                    = 0x8
	PARODD                    = 0x200
	PENDIN                    = 0x4000
	PRIO_PGRP                 = 0x1
	PRIO_PROCESS              = 0x0
	PRIO_USER                 = 0x2
	PROT_EXEC                 = 0x4
	PROT_NONE                 = 0x0
	PROT_READ                 = 0x1
	PROT_WRITE                = 0x2
	RLIMIT_AS                 = 0x6
	RLIMIT_CORE               = 0x0
	RLIMIT_CPU                = 0x1
	RLIMIT_DATA               = 0x2
	RLIMIT_FSIZE              = 0x3
	RLIMIT_NOFILE             = 0x4
	RLIMIT_STACK              = 0x5
	RLIM_INFINITY             = 0xffffffff
	RTF_BLACKHOLE             = 0x1000
	RTF_DEFAULT               = 0x80
	RTF_DYNAMIC               = 0x10
	RTF_GATEWAY               = 0x2
	RTF_HOST                  = 0x4
	RTF_LOCAL                 = 0x200000
	RTF_MODIFIED              = 0x20
	RTF_REJECT                = 0x8
	RTF_STATIC                = 0x800
	RTF_UP                    = 0x1
	RUSAGE_CHILDREN           = -0x1
	RUSAGE_SELF               = 0x0
	SCM_RIGHTS                = 0x1
	SEEK_CUR                  = 0x1
	SEEK_DATA                 = 0x3
	SEEK_END                  = 0x2
	SEEK_HOLE                 = 0x4
	SEEK_SET                  = 0x0
	SHUT_RD                   = 0x0
	SHUT_RDWR                 = 0x2
	SHUT_WR                   = 0x1
	SOCK_DGRAM                = 0x2
	SOCK_MISC                 = 0xff
	SOCK_RAW                  = 0x3
	SOCK_SEQPACKET            = 0x5
	SOCK_STREAM               = 0x1
	SOL_SOCKET                = -0x1
	SOMAXCONN                 = 0x20
	SO_ACCEPTCONN             = 0x1
	SO_BINDTODEVICE           = 0x4000000a
	SO_BROADCAST              = 0x2
	SO_DEBUG                  = 0x4
	SO_DONTROUTE              = 0x8
	SO_ERROR                  = 0x40000007
	SO_KEEPALIVE              = 0x10
	SO_LINGER                 = 0x200
	SO_NONBLOCK               = 0x40000009
	SO_OOBINLINE              = 0x20
	SO_PEERCRED               = 0x4000000b
	SO_RCVBUF                 = 0x40000004
	SO_RCVLOWAT               = 0x40000005
	SO_RCVTIMEO               = 0x40000006
	SO_REUSEADDR              = 0x40
	SO_REUSEPORT              = 0x80
	SO_SNDBUF                 = 0x40000001
	SO_SNDLOWAT               = 0x40000002
	SO_SNDTIMEO               = 0x40000003
	SO_TYPE                   = 0x40000008
	SO_USELOOPBACK            = 0x100
	S_ALLOW_DUPS              = 0x80000
	S_ATTR                    = 0x10000000
	S_ATTR_DIR                = 0x8000000
	S_DOUBLE_INDEX            = 0x40000
	S_FLOAT_INDEX             = 0x800000
	S_IEXEC                   = 0x40
	S_IFBLK                   = 0x6000
	S_IFCHR                   = 0x2000
	S_IFDIR                   = 0x4000
	S_IFIFO                   = 0x1000
	S_IFLNK                   = 0xa000
	S_IFMT                    = 0xf000
	S_IFREG                   = 0x8000
	S_IFSOCK                  = 0xc000
	S_INDEX_DIR               = 0x20000000
	S_INT_INDEX               = 0x2000000
	S_IREAD                   = 0x100
	S_IRGRP                   = 0x20
	S_IROTH                   = 0x4
	S_IRUSR                   = 0x100
	S_IRWXG                   = 0x38
	S_IRWXO                   = 0x7
	S_IRWXU                   = 0x1c0
	S_ISGID                   = 0x400
	S_ISUID                   = 0x800
	S_ISVTX                   = 0x200
	S_IUMSK                   = 0xfff
	S_IWGRP                   = 0x10
	S_IWOTH                   = 0x2
	S_IWRITE                  = 0x80
	S_IWUSR                   = 0x80
	S_IXGRP                   = 0x8
	S_IXOTH                   = 0x1
	S_IXUSR                   = 0x40
	S_LINK_AUTO_DELETE        = 0x80000
	S_LINK_SELF_HEALING       = 0x40000
	S_LONG_LONG_INDEX         = 0x200000
	S_STR_INDEX               = 0x1000000
	S_UINT_INDEX              = 0x4000000
	S_ULONG_LONG_INDEX        = 0x400000
	TAB0                      = 0x0
	TAB1                      = 0x800
	TAB2                      = 0x1000
	TAB3                      = 0x1800
	TABDLY                    = 0x1800
	TCFLSH                    = 0x8006
	TCGETA                    = 0x8000
	TCGETBITS                 = 0x8009
	TCIFLUSH                  = 0x1
	TCIOFF                    = 0x4
	TCIOFLUSH                 = 0x3
	TCION                     = 0x8
	TCOFLUSH                  = 0x2
	TCOOFF                    = 0x1
	TCOON                     = 0x2
	TCP_MAXSEG                = 0x2
	TCP_NODELAY               = 0x1
	TCP_NOOPT                 = 0x8
	TCP_NOPUSH                = 0x4
	TCSAFLUSH                 = 0x4
	TCSBRK                    = 0x8005
	TCSETA                    = 0x8001
	TCSETAF                   = 0x8002
	TCSETAW                   = 0x8003
	TCSETDTR                  = 0x800a
	TCSETRTS                  = 0x800b
	TCXONC                    = 0x8007
	TIMER_ABSTIME             = 0x1
	TIOCCBRK                  = 0x8015
	TIOCGPGRP                 = 0x800f
	TIOCGSID                  = 0x8018
	TIOCGWINSZ                = 0x800c
	TIOCMBIC                  = 0x8017
	TIOCMBIS                  = 0x8016
	TIOCMGET                  = 0x8012
	TIOCMSET                  = 0x8013
	TIOCM_CAR                 = 0x8
	TIOCM_CD                  = 0x8
	TIOCM_CTS                 = 0x1
	TIOCM_DSR                 = 0x2
	TIOCM_DTR                 = 0x10
	TIOCM_RI                  = 0x4
	TIOCM_RTS                 = 0x20
	TIOCSBRK                  = 0x8014
	TIOCSCTTY                 = 0x8011
	TIOCSPGRP                 = 0x8010
	TIOCSWINSZ                = 0x800d
	TOSTOP                    = 0x100
	UTIME_NOW                 = 0x3b9aca00
	UTIME_OMIT                = 0x3b9aca01
	VEOF                      = 0x4
	VEOL                      = 0x5
	VEOL2                     = 0x6
	VERASE                    = 0x2
	VINTR                     = 0x0
	VKILL                     = 0x3
	VMIN                      = 0x4
	VQUIT                     = 0x1
	VSTART                    = 0x8
	VSTOP                     = 0x9
	VSUSP                     = 0xa
	VSWTCH                    = 0x7
	VT0                       = 0x0
	VT1                       = 0x4000
	VTDLY                     = 0x4000
	VTIME                     = 0x5
	XCASE                     = 0x4
)

// Errors
const (
	E2BIG           = syscall.Errno(-0x7fff8fff & 0xffffffff)
	EACCES          = syscall.Errno(-0x7ffffffe & 0xffffffff)
	EADDRINUSE      = syscall.Errno(-0x7fff8fea & 0xffffffff)
	EADDRNOTAVAIL   = syscall.Errno(-0x7fff8fe9 & 0xffffffff)
	EAFNOSUPPORT    = syscall.Errno(-0x7fff8feb & 0xffffffff)
	EAGAIN          = syscall.Errno(-0x7ffffff5 & 0xffffffff)
	EALREADY        = syscall.Errno(-0x7fff8fdb & 0xffffffff)
	EBADF           = syscall.Errno(-0x7fffa000 & 0xffffffff)
	EBADMSG         = syscall.Errno(-0x7fff8fd2 & 0xffffffff)
	EBUSY           = syscall.Errno(-0x7ffffff2 & 0xffffffff)
	ECANCELED       = syscall.Errno(-0x7fff8fd1 & 0xffffffff)
	ECHILD          = syscall.Errno(-0x7fff8ffe & 0xffffffff)
	ECONNABORTED    = syscall.Errno(-0x7fff8fe5 & 0xffffffff)
	ECONNREFUSED    = syscall.Errno(-0x7fff8fe0 & 0xffffffff)
	ECONNRESET      = syscall.Errno(-0x7fff8fe4 & 0xffffffff)
	EDEADLK         = syscall.Errno(-0x7fff8ffd & 0xffffffff)
	EDESTADDRREQ    = syscall.Errno(-0x7fff8fd0 & 0xffffffff)
	EDOM            = syscall.Errno(-0x7fff8ff0 & 0xffffffff)
	EDOOFUS         = syscall.Errno(-0x7ffffffb & 0xffffffff)
	EDQUOT          = syscall.Errno(-0x7fff8fcf & 0xffffffff)
	EEXIST          = syscall.Errno(-0x7fff9ffe & 0xffffffff)
	EFAULT          = syscall.Errno(-0x7fffecff & 0xffffffff)
	EFBIG           = syscall.Errno(-0x7fff8ffc & 0xffffffff)
	EFPOS           = syscall.Errno(-0x7fff8ff2 & 0xffffffff)
	EHOSTDOWN       = syscall.Errno(-0x7fff8fd3 & 0xffffffff)
	EHOSTUNREACH    = syscall.Errno(-0x7fff8fdf & 0xffffffff)
	EIDRM           = syscall.Errno(-0x7fff8fce & 0xffffffff)
	EILSEQ          = syscall.Errno(-0x7fff8fda & 0xffffffff)
	EINPROGRESS     = syscall.Errno(-0x7fff8fdc & 0xffffffff)
	EINTR           = syscall.Errno(-0x7ffffff6 & 0xffffffff)
	EINVAL          = syscall.Errno(-0x7ffffffb & 0xffffffff)
	EIO             = syscall.Errno(-0x7fffffff & 0xffffffff)
	EISCONN         = syscall.Errno(-0x7fff8fe3 & 0xffffffff)
	EISDIR          = syscall.Errno(-0x7fff9ff7 & 0xffffffff)
	ELOOP           = syscall.Errno(-0x7fff9ff4 & 0xffffffff)
	EMFILE          = syscall.Errno(-0x7fff9ff6 & 0xffffffff)
	EMLINK          = syscall.Errno(-0x7fff8ffb & 0xffffffff)
	EMSGSIZE        = syscall.Errno(-0x7fff8fd6 & 0xffffffff)
	EMULTIHOP       = syscall.Errno(-0x7fff8fcd & 0xffffffff)
	ENAMETOOLONG    = syscall.Errno(-0x7fff9ffc & 0xffffffff)
	ENETDOWN        = syscall.Errno(-0x7fff8fe8 & 0xffffffff)
	ENETRESET       = syscall.Errno(-0x7fff8fe6 & 0xffffffff)
	ENETUNREACH     = syscall.Errno(-0x7fff8fe7 & 0xffffffff)
	ENFILE          = syscall.Errno(-0x7fff8ffa & 0xffffffff)
	ENOATTR         = syscall.Errno(-0x7fff8fc4 & 0xffffffff)
	ENOBUFS         = syscall.Errno(-0x7fff8fdd & 0xffffffff)
	ENODATA         = syscall.Errno(-0x7fff8fcc & 0xffffffff)
	ENODEV          = syscall.Errno(-0x7fff8ff9 & 0xffffffff)
	ENOENT          = syscall.Errno(-0x7fff9ffd & 0xffffffff)
	ENOERR          = syscall.Errno(0x0 & 0xffffffff)
	ENOEXEC         = syscall.Errno(-0x7fffecfe & 0xffffffff)
	ENOLCK          = syscall.Errno(-0x7fff8ff8 & 0xffffffff)
	ENOLINK         = syscall.Errno(-0x7fff8fcb & 0xffffffff)
	ENOMEM          = syscall.Errno(-0x80000000 & 0xffffffff)
	ENOMSG          = syscall.Errno(-0x7fff8fd9 & 0xffffffff)
	ENOPROTOOPT     = syscall.Errno(-0x7fff8fde & 0xffffffff)
	ENOSPC          = syscall.Errno(-0x7fff9ff9 & 0xffffffff)
	ENOSR           = syscall.Errno(-0x7fff8fca & 0xffffffff)
	ENOSTR          = syscall.Errno(-0x7fff8fc9 & 0xffffffff)
	ENOSYS          = syscall.Errno(-0x7fff8ff7 & 0xffffffff)
	ENOTCONN        = syscall.Errno(-0x7fff8fe2 & 0xffffffff)
	ENOTDIR         = syscall.Errno(-0x7fff9ffb & 0xffffffff)
	ENOTEMPTY       = syscall.Errno(-0x7fff9ffa & 0xffffffff)
	ENOTRECOVERABLE = syscall.Errno(-0x7fff8fc3 & 0xffffffff)
	ENOTSOCK        = syscall.Errno(-0x7fff8fd4 & 0xffffffff)
	ENOTSUP         = syscall.Errno(-0x7fff8fc8 & 0xffffffff)
	ENOTTY          = syscall.Errno(-0x7fff8ff6 & 0xffffffff)
	ENXIO           = syscall.Errno(-0x7fff8ff5 & 0xffffffff)
	EOK             = syscall.Errno(0x0 & 0xffffffff)
	EOPNOTSUPP      = syscall.Errno(-0x7fff8fd5 & 0xffffffff)
	EOVERFLOW       = syscall.Errno(-0x7fff8fd7 & 0xffffffff)
	EOWNERDEAD      = syscall.Errno(-0x7fff8fc2 & 0xffffffff)
	EPERM           = syscall.Errno(-0x7ffffff1 & 0xffffffff)
	EPFNOSUPPORT    = syscall.Errno(-0x7fff8fec & 0xffffffff)
	EPIPE           = syscall.Errno(-0x7fff9ff3 & 0xffffffff)
	EPROTO          = syscall.Errno(-0x7fff8fc7 & 0xffffffff)
	EPROTONOSUPPORT = syscall.Errno(-0x7fff8fed & 0xffffffff)
	EPROTOTYPE      = syscall.Errno(-0x7fff8fee & 0xffffffff)
	ERANGE          = syscall.Errno(-0x7fff8fef & 0xffffffff)
	EROFS           = syscall.Errno(-0x7fff9ff8 & 0xffffffff)
	ESHUTDOWN       = syscall.Errno(-0x7fff8fe1 & 0xffffffff)
	ESIGPARM        = syscall.Errno(-0x7fff8ff1 & 0xffffffff)
	ESPIPE          = syscall.Errno(-0x7fff8ff4 & 0xffffffff)
	ESRCH           = syscall.Errno(-0x7fff8ff3 & 0xffffffff)
	ESTALE          = syscall.Errno(-0x7fff8fd8 & 0xffffffff)
	ETIME           = syscall.Errno(-0x7fff8fc6 & 0xffffffff)
	ETIMEDOUT       = syscall.Errno(-0x7ffffff7 & 0xffffffff)
	ETXTBSY         = syscall.Errno(-0x7fff8fc5 & 0xffffffff)
	EWOULDBLOCK     = syscall.Errno(-0x7ffffff5 & 0xffffffff)
	EXDEV           = syscall.Errno(-0x7fff9ff5 & 0xffffffff)
)

// Signals
const (
	SIGABRT      = syscall.Signal(0x6)
	SIGALRM      = syscall.Signal(0xe)
	SIGBUS       = syscall.Signal(0x1e)
	SIGCHLD      = syscall.Signal(0x5)
	SIGCONT      = syscall.Signal(0xc)
	SIGFPE       = syscall.Signal(0x8)
	SIGHUP       = syscall.Signal(0x1)
	SIGILL       = syscall.Signal(0x4)
	SIGINT       = syscall.Signal(0x2)
	SIGKILL      = syscall.Signal(0x9)
	SIGKILLTHR   = syscall.Signal(0x15)
	SIGPIPE      = syscall.Signal(0x7)
	SIGPOLL      = syscall.Signal(0x17)
	SIGPROF      = syscall.Signal(0x18)
	SIGQUIT      = syscall.Signal(0x3)
	SIGRESERVED1 = syscall.Signal(0x1f)
	SIGRESERVED2 = syscall.Signal(0x20)
	SIGSEGV      = syscall.Signal(0xb)
	SIGSTOP      = syscall.Signal(0xa)
	SIGSYS       = syscall.Signal(0x19)
	SIGTERM      = syscall.Signal(0xf)
	SIGTRAP      = syscall.Signal(0x16)
	SIGTSTP      = syscall.Signal(0xd)
	SIGTTIN      = syscall.Signal(0x10)
	SIGTTOU      = syscall.Signal(0x11)
	SIGURG       = syscall.Signal(0x1a)
	SIGUSR1      = syscall.Signal(0x12)
	SIGUSR2      = syscall.Signal(0x13)
	SIGVTALRM    = syscall.Signal(0x1b)
	SIGWINCH     = syscall.Signal(0x14)
	SIGXCPU      = syscall.Signal(0x1c)
	SIGXFSZ      = syscall.Signal(0x1d)
)

// Error table
var errorList = [...]struct {
	num  syscall.Errno
	name string
	desc string
}{
	{1, "ENOMEM", "out of memory"},
	{2, "EIO", "I/O error"},
	{3, "EACCES", "permission denied"},
	{6, "EINVAL", "invalid Argument"},
	{10, "ETIMEDOUT", "operation timed out"},
	{11, "EINTR", "interrupted system call"},
	{12, "EAGAIN", "operation would block"},
	{15, "EBUSY", "device/File/Resource busy"},
	{16, "EPERM", "operation not allowed"},
	{4866, "EFAULT", "bad address"},
	{4867, "ENOEXEC", "not an executable"},
	{24577, "EBADF", "bad file descriptor"},
	{24579, "EEXIST", "file or Directory already exists"},
	{24580, "ENOENT", "no such file or directory"},
	{24581, "ENAMETOOLONG", "file name too long"},
	{24582, "ENOTDIR", "not a directory"},
	{24583, "ENOTEMPTY", "directory not empty"},
	{24584, "ENOSPC", "no space left on device"},
	{24585, "EROFS", "read-only file system"},
	{24586, "EISDIR", "is a directory"},
	{24587, "EMFILE", "too many open files"},
	{24588, "EXDEV", "cross-device link"},
	{24589, "ELOOP", "too many symbolic links"},
	{24590, "EPIPE", "broken pipe"},
	{28674, "E2BIG", "argument too big"},
	{28675, "ECHILD", "no child process"},
	{28676, "EDEADLK", "resource deadlock"},
	{28677, "EFBIG", "file too large"},
	{28678, "EMLINK", "too many links"},
	{28679, "ENFILE", "file table overflow"},
	{28680, "ENODEV", "no such device"},
	{28681, "ENOLCK", "no record locks available"},
	{28682, "ENOSYS", "function not implemented"},
	{28683, "ENOTTY", "not a tty"},
	{28684, "ENXIO", "device not accessible"},
	{28685, "ESPIPE", "seek not allowed on file descriptor"},
	{28686, "ESRCH", "no such process"},
	{28687, "EFPOS", "file Position Error"},
	{28688, "ESIGPARM", "signal Error"},
	{28689, "EDOM", "numerical argument out of range"},
	{28690, "ERANGE", "range Error"},
	{28691, "EPROTOTYPE", "protocol wrong type for socket"},
	{28692, "EPROTONOSUPPORT", "protocol not supported"},
	{28693, "EPFNOSUPPORT", "protocol family not supported"},
	{28694, "EAFNOSUPPORT", "address family not supported by protocol family"},
	{28695, "EADDRINUSE", "address already in use"},
	{28696, "EADDRNOTAVAIL", "can't assign requested address"},
	{28697, "ENETDOWN", "network is down"},
	{28698, "ENETUNREACH", "network is unreachable"},
	{28699, "ENETRESET", "network dropped connection on reset"},
	{28700, "ECONNABORTED", "software caused connection abort"},
	{28701, "ECONNRESET", "connection reset by peer"},
	{28702, "EISCONN", "socket is already connected"},
	{28703, "ENOTCONN", "socket is not connected"},
	{28704, "ESHUTDOWN", "can't send after socket shutdown"},
	{28705, "ECONNREFUSED", "connection refused"},
	{28706, "EHOSTUNREACH", "no route to host"},
	{28707, "ENOPROTOOPT", "protocol option not available"},
	{28708, "ENOBUFS", "no buffer space available"},
	{28709, "EINPROGRESS", "operation now in progress"},
	{28710, "EALREADY", "operation already in progress"},
	{28711, "EILSEQ", "illegal byte sequence"},
	{28712, "ENOMSG", "no message of desired type"},
	{28713, "ESTALE", "stale file handle"},
	{28714, "EOVERFLOW", "value too large for defined type"},
	{28715, "EMSGSIZE", "message too long"},
	{28716, "EOPNOTSUPP", "operation not supported"},
	{28717, "ENOTSOCK", "socket operation on non-socket"},
	{28718, "EHOSTDOWN", "host is down"},
	{28719, "EBADMSG", "bad message"},
	{28720, "ECANCELED", "operation canceled"},
	{28721, "EDESTADDRREQ", "destination address required"},
	{28722, "EDQUOT", "reserved"},
	{28723, "EIDRM", "identifier removed"},
	{28724, "EMULTIHOP", "reserved"},
	{28725, "ENODATA", "no message available"},
	{28726, "ENOLINK", "reserved"},
	{28727, "ENOSR", "no STREAM resources"},
	{28728, "ENOSTR", "not a STREAM"},
	{28729, "ENOTSUP", "not supported"},
	{28730, "EPROTO", "protocol error"},
	{28731, "ETIME", "STREAM ioctl() timeout"},
	{28732, "ETXTBSY", "text file busy"},
	{28733, "ENOATTR", "no such attribute"},
	{28734, "ENOTRECOVERABLE", "state not recoverable"},
	{28735, "EOWNERDEAD", "previous owner died"},
	{0, "ENOERR", "no error"},
}

// Signal table
var signalList = [...]struct {
	num  syscall.Signal
	name string
	desc string
}{
	{1, "SIGHUP", "hangup"},
	{2, "SIGINT", "interrupt"},
	{3, "SIGQUIT", "quit"},
	{4, "SIGILL", "illegal instruction"},
	{5, "SIGCHLD", "child exited"},
	{6, "SIGABRT", "abort"},
	{7, "SIGPIPE", "broken pipe"},
	{8, "SIGFPE", "floating point exception"},
	{9, "SIGKILL", "killed (by death)"},
	{10, "SIGSTOP", "stopped"},
	{11, "SIGSEGV", "segmentation violation"},
	{12, "SIGCONT", "continued"},
	{13, "SIGTSTP", "stopped (tty output)"},
	{14, "SIGALRM", "alarm"},
	{15, "SIGTERM", "termination requested"},
	{16, "SIGTTIN", "stopped (tty input)"},
	{17, "SIGTTOU", "stopped (tty output)"},
	{18, "SIGUSR1", "user defined signal 1"},
	{19, "SIGUSR2", "user defined signal 2"},
	{20, "SIGWINCH", "window size changed"},
	{21, "SIGKILLTHR", "kill Thread"},
	{22, "SIGTRAP", "trace/breakpoint trap"},
	{23, "SIGPOLL", "pollable event"},
	{24, "SIGPROF", "profiling timer expired"},
	{25, "SIGSYS", "bad system call"},
	{26, "SIGURG", "high bandwidth data is available at socket"},
	{27, "SIGVTALRM", "virtual timer expired"},
	{28, "SIGXCPU", "CPU time limit exceeded"},
	{29, "SIGXFSZ", "file size limit exceeded"},
	{30, "SIGBUS", "bus error"},
	{31, "SIGRESERVED1", "reserved signal 1"},
	{32, "SIGRESERVED2", "reserved signal 2"},
}
